export default `<?xml version="1.0" encoding="utf-8"?>
<RacunZahtjev
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<BrojZahtjeva>{{requestId}}</BrojZahtjeva>
	<VrstaZahtjeva>2</VrstaZahtjeva>
	<NoviObjekat>
        {{#buyer}}
		<Kupac>
			<IDbroj>{{id}}</IDbroj>
			<Naziv>{{name}}</Naziv>
			<Adresa>{{address}}</Adresa>
			<PostanskiBroj>{{zipCode}}</PostanskiBroj>
			<Grad>{{city}}</Grad>
		</Kupac>
        {{/buyer}}
		<StavkeRacuna>
            {{#articles}}
			<RacunStavka>
				<artikal>
					<Sifra>{{id}}</Sifra>
					<Naziv>{{name}}</Naziv>
					<JM>{{unit}}</JM>
					<Cijena>{{price}}</Cijena>
					<Stopa>{{rate}}</Stopa>
				</artikal>
				<Kolicina>{{quantity}}</Kolicina>
				<Rabat>{{discount}}</Rabat>
			</RacunStavka>
            {{/articles}}
		</StavkeRacuna>
		<VrstePlacanja>
            {{#refunds}}
			<VrstaPlacanja>
				<Oznaka>{{type}}</Oznaka>
				<Iznos>{{signedAmount}}</Iznos>
			</VrstaPlacanja>
            {{/refunds}}
		</VrstePlacanja>
		<Napomena>{{note}}</Napomena>
		<BrojRacuna>{{originalReceiptId}}</BrojRacuna>
	</NoviObjekat>
</RacunZahtjev>`;
